language: generic 
sudo: required
services:
  - docker
before_install: 
  - docker build -t andrzejcz/docker-react -f Dockerfile.dev . 
script: 
  -docker run -e CI=trueandrzejcz/docker-react npm run test 