version: '3'
services:
  web:
    #build defines where to find project files to build container image
    stdin_open: true
    build: 
    #below we say: look in my current working dir for dockerfile.dev to build the image
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]